version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - cheersbeer
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: source-map-url
    versions:
    - 0.4.1
  - dependency-name: husky
    versions:
    - 5.2.0
