version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - 'cheersbeer'
    default_labels:
      - 'dependencies'
    allowed_updates:
      - match:
          update_type: 'all'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
      - match:
          dependency_type: 'production'
          update_type: 'semver:minor'
    version_requirement_updates: 'increase_versions'
